export const youtubeReels = [
  "2mGsyVlC5YQ",
  "lF7nXuMr8UU",
  "OmSKEzFk1rI",
  "n90V4QBGvYo",
  "Gq1hGUvYuVY",
  "PWCiQ74lygc",
  "ovEs2MUNOHM",
  "E2x9nOA9aJ8",
  "ZAc8Z8GvWrI",
  "aYlzD_M2G5k",
  "kREXc8ugivE",
  "s3gJzYhFJhk",
  "K3pbWMIJ6kI",
  "hPR9dWNg5fY",
  "vT_1c9h5PJE",
  "RRo91F2oL8k",
  "AQc2poamT2M",
  "R3reWdTUN5w",
  "AUUN9XBbomY",
  "k8oQpPCAg0o",
  "wYK7CSKS0No",
  "Sd-AEeR6wII",
  "ewwpMy_vgHQ",
  "l34XZQglpck",
];

export const youtubeStories = [
  "4h04aFuogI4",
  "qix6kDJsHYM",
  "HvS2UGCIDfY",
  "zbpn4acLlwU",
  "CdAM4FyCv0A",
  "9zLl6utV1FM",
  "aCkIZgEcVKg",
  "2UNPsl5BVaM",
  "wrjZ9fLaasI",
  "5kePkrCacPY",
];

// These were unused in the main component but kept here for reference if needed
export const localReels = [
  "/videos/reels/sizzling-brownie.mp4",
  "/videos/reels/platinum-events.mp4",
  "/videos/reels/treat-studio-madam-ji.mp4",
  "/videos/reels/treat-studio-reel.mp4",
  "/videos/reels/tumble-dry-final.mp4",
  "/videos/reels/tumble-reel-3.mp4",
  "/videos/reels/reel-1.mp4",
  "/videos/reels/reel-2.mov",
  "/videos/reels/reel-3.mp4",
  "/videos/reels/reel-4.mp4",
  "/videos/reels/reel-5.mp4",
  "/videos/reels/reel-6.mp4",
  "/videos/reels/reel-7.mp4",
  "/videos/reels/reel-8.mp4",
  "/videos/reels/reel-9.mp4",
  "/videos/reels/reel-10.mov",
  "/videos/reels/reel-11.mp4",
  "/videos/reels/reel-12.mp4",
  "/videos/reels/reel-13.mp4",
  "/videos/reels/reel-14.mp4",
  "/videos/reels/reel-15.mp4",
  "/videos/reels/reel-16.mp4",
  "/videos/reels/reel-17.mp4",
  "/videos/reels/reel-18.mp4",
  "/videos/reels/reel-19.mp4",
  "/videos/reels/reel-20.mp4",
  "/videos/reels/reel-21.mp4",
  "/videos/reels/reel-22.mov",
  "/videos/reels/reel-23.mp4",
  "/videos/reels/reel-24.mp4",
  "/videos/reels/reel-25.mp4",
  "/videos/reels/reel-26.mp4",
];

export const localPosters = [
  "/images/posters/poster-1.jpg",
  "/images/posters/poster-2.jpg",
  "/images/posters/poster-3.jpg",
  "/images/posters/poster-4.jpg",
  "/images/posters/poster-5.jpg",
  "/images/posters/poster-6.png",
  "/images/posters/poster-7.jpg",
  "/images/posters/poster-8.jpg",
  "/images/posters/poster-9.png",
  "/images/posters/poster-10.jpg",
];

export const localStories = [
  "/videos/stories/fries.mp4",
  "/videos/stories/garlic-potato-pops.mp4",
  "/videos/stories/honey-chilli-potato.mp4",
  "/videos/stories/honey-chilli-story.mp4",
  "/videos/stories/korean-fries.mp4",
  "/videos/stories/nacho-stories.mp4",
  "/videos/stories/pancake.mp4",
  "/videos/stories/pasta-story.mp4",
  "/videos/stories/pink-alfredo-pasta.mp4",
  "/videos/stories/potato-twister-story.mp4",
  "/videos/stories/potato-twister-story-2.mp4",
  "/videos/stories/tumble-dry-post.mp4",
  "/videos/stories/story.mp4",
  "/videos/stories/story-20250807.mp4",
];
